api/urls.py
from django.urls import path

from api.views import BookReviewDetailAPIView, BookReviewsAPIView
from rest_framework import routers
from api.views import BookReviewViewSet


app_name = 'api'

# router = routers.DefaultRouter()
# router.register('review', BookReviewViewSet, basename='review')
# urlpatterns = router.urls

urlpatterns = [
    path("reviews/", BookReviewsAPIView.as_view(), name="review-list"),

    path("reviews/<int:id>/", BookReviewDetailAPIView.as_view(), name="review-detail"),
]

books/urls.py
from django.urls import path
from books.views import BooksView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView

app_name = 'books'
urlpatterns = [
    path("", BooksView.as_view(), name="list"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/confirm/",
         ConfirmDeleteReviewView.as_view(),
         name="confirm-delete-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/",
         DeleteReviewView.as_view(),
         name="delete-review"),

]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, home_page

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home_page, name='home_page'),
    path('books/', include('books.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
]

templates/base.html
{% load static %}

{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url 'users:profile' as profile_page_url %}
{% url 'users:profile_edit' as profile_edit_page_url %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Goodreads Clone{% endblock %}</title>

    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">    

    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">

</head>
<body class="mx-5">

<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads Clone</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{{ home_page_url }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == books_page_url %} active {% endif %}" aria-current="page" href="{{ books_page_url }}">Books</a>
                </li>
            </ul>
        <div class="me-5">
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav">  
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {% if request.path == profile_page_url or request.path == profile_edit_page_url %} active {% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ request.user.username }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ profile_page_url }}">Profile</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'users:register' %}">Register</a>
                    <a class="btn btn-primary" href="{% url 'users:login' %}">Login</a>
                {% endif %}
            </div>
        
        </div>
    </div>
</nav>


<div class="container">
    {% if messages %}
        <div class="mt-4">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        </div>
    {% endif %}
        

    {% block content %}{% endblock %}
</div>

<!-- Js -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home Page{% endblock %}

{% block content %}
	<h1>All reviews</h1>
    
    {% for review in page_obj %}
        <div class="container posts-content">
            <div class="row">
                <div class="col-lg-6">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="media mb-3">
                                <div class="media-body ml-3">
                                    <img src="{{ review.user.profile_picture.url }}" class="d-block ui-w-40 rounded-circle" alt="">
                                    <b>{{ review.user.username }}</b> rated this book {{ review.stars_given }} stars
                                    <div class="text-muted small">{{ review.created_at | date:"M d, Y" }}</div>
                                </div>
                            </div>
                            <p>
                                {{ review.comment | truncatechars:300 }}
                            </p>
                            <img class="cover-pic center" src="{{ review.book.cover_picture.url }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    {% endfor %}
    
    <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page_item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                <li class="page_item"><a class="page-link"
                                         href="?page=?page={{ page_obj.previous_page_number }}">previous</a></li>
            {% endif %}

            <li class="page_item-active">
                <a href="#" class="page-link">{{ page_obj.number }}</a>
            </li>

            {% if page_obj.has_next %}
                <li class="page_item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                <li class="page_item"><a class="page-link" href="?page={{ page_obj.num_pages }}">last &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    
    
{% endblock %}

templates/landing.html
{% extends 'base.html' %}


{% block content %}
	<h1>Landing Page</h1>
{% endblock %}